name: zKitPvP
version: '${project.version}'
main: dev.gabbo.zkitpvp.KitPvP
authors: [ ImGqbbo ]
description: KitPvP plugin for Spigot/Paper servers
softdepend: [ PlaceholderAPI ]
commands:
  kitpvp:
    description: Main command for everything
    aliases: [ kp, zkitpvp ]
  spawn:
    description: Teleport player to spawn
  dropsettings:
    description: Command to manage the pickup settings
    aliases: [ drops, drop-settings ]
  fix:
    description: Fixes inventory
    aliases: [ fixall ]
  giveexp:
    description: Transfer a speciefied amount of levels to another player
    aliases: [ givelevels, expgive, paylevels, payexp ]